### PR TITLE
fix(control_flow): handle class constructors

### LINKED ISSUE #353: bug: unconditional return in constructor produces unreachable code after class
An unconditional return statement inside of a class constructor also leads to a "unreachable" linting error:

```ts
class Class {
  constructor() {
    return this;
  }
}

console.log("unreachable???");
```
```
(no-unreachable) This statement is unreachable
console.log("unreachable???");
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    at \deno-lint.ts:7:0

Found 1 problem
Checked 1 file
```

A conditional return however does not produce an error:
```ts
class Class {
  constructor() {
    if (Deno) return this;
  }
}

console.log("unreachable???");
```

_Originally posted in https://github.com/denoland/deno_lint/issues/318#issuecomment-702154495_

### PR DESCRIPTION
**Pull request by magurotuna**
Fixes #353

### CODE REVIEW

File: src/rules/no_unreachable.rs [hunk 1]
```diff
@@ -603,4 +603,35 @@ function normalize(type: string): string | undefined {
       "#,
     );
   }
+
+  // https://github.com/denoland/deno_lint/issues/353
+  #[test]
+  fn issue_353_1() {
```
Comment (bartlomieju) [inline src/rules/no_unreachable.rs:609]: 👍

**Review by bartlomieju — APPROVED** [review]
Nice fix
