### PR TITLE
fix(control-flow): analyze try statements in correct order

### LINKED ISSUE #1031: Problem in `finally` block
Not a big issue but I don't think `deno lint` should throw a `no-unreachable` problem here. I could prevent the problem by moving the `return` statement outside the block.

### Lint Name
`no-unreachable`

### Code Snippet

```ts
private async handleContext(ctx: Context<S>): Promise<Response> {
    try {
      ctx = await this.invokeHandlers(ctx, this.routes);
    } catch (error) {
      ctx.error = error;
      ctx = await this.invokeHandlers(ctx, this.catchRoutes);
    } finally {
      ctx = await this.invokeHandlers(ctx, this.finallyRoutes);
      return ctx.response;
    }
  }
```

### Expected Result

Nothing being thrown

### Version

deno 1.20.1 (release, x86_64-unknown-linux-gnu)
v8 10.0.139.6
typescript 4.6.2

### PR DESCRIPTION
**Pull request by ah-yu**
Closes #1031

### CODE REVIEW

File: src/control_flow/analyze_test.rs [hunk 1]
```diff
@@ -585,7 +585,7 @@ function foo() {
     false,
     Some(End::Forced {
       ret: true,
-      throw: true,
+      throw: false,
```
Comment (ah-yu) [inline src/control_flow/analyze_test.rs:588]: The try statement in this test case won't throw.

File: src/control_flow/analyze_test.rs [hunk 2]
```diff
@@ -503,7 +503,7 @@ function foo() {
...
```
Comment (ah-yu) [inline src/control_flow/analyze_test.rs:506]: The try statement in this test case won't throw.

**Review by bartlomieju — APPROVED** [review]
LGTM! Nice fix, thank you @ah-yu
