### PR TITLE
fix: nullish coalescing operator conditional detection

### LINKED ISSUE #1426: Lint rule react-rules-of-hooks misidentifies a conditional hook
When using the new lint rules, deno falsely identifies the `useState` as conditional.

Example can be seen on this repo [here](https://github.com/paul-sachs/deno-react/blob/psachs/linting-bug/client/src/App.tsx#L43)

### Lint Name

react-rules-of-hooks

### Code Snippet

```tsx
const Comp = () => {
  useDocumentTitle(`Subscription · ${owner ?? ""}`);

  const [count, setCount] = useState(0);

  return null
}
```

### Expected Result

No error

### Actual Result

Identifies `useState` as conditional.

### Version

deno 2.2.2 (stable, release, aarch64-apple-darwin)
v8 13.4.114.9-rusty
typescript 5.7.3

### PR DESCRIPTION
**Pull request by paul-sachs**
Need to pop conditional on binary expression exits.

Fixes #1426

### CODE REVIEW

**Comment by paul-sachs** [comment]
First rust PR soooo... 🙈

File: src/rules/react_rules_of_hooks.rs [hunk 1]
```diff
@@ -185,9 +185,13 @@ impl Handler for RulesOfHooksHandler {
           }
         }
       }
+      Node::BinExpr(_) => {
+        if let Some(ParentKind::Bin) = self.parent_kind.pop() {
```
Comment (paul-sachs) [inline src/rules/react_rules_of_hooks.rs:189]: Not sure if this is even really needed, might be excessive paranoia.

**Review by marvinhagemeister — APPROVED** [review]
Sweet, thanks!
